---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "monitoring-plugins-alpine_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'alpine'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon1"
  arch: "amd64"
  asset_filename: "monitoring-plugins-amazon1_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.platform_version.split('.')[0] == '2018'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon2"
  arch: "amd64"
  asset_filename: "monitoring-plugins-amazon2_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.platform_version == '2'"
  - "entity.system.arch == 'amd64'"

- platform: "centos6"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos6_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '6'"
  - "entity.system.arch == 'amd64'"

- platform: "centos7"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos7_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '7'"
  - "entity.system.arch == 'amd64'"

- platform: "debian8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

- platform: "debian9"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian9_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '9'"
  - "entity.system.arch == 'amd64'"

- platform: "debian10"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian10_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '10'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1604"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu1604_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '16'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1804"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu1804_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '18'"
  - "entity.system.arch == 'amd64'"
