language: c
compiler:
- gcc
services:
- docker
script:
- "./travis-build.sh"
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git
  bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: script
  script: "./travis-github-upload.sh"
  cleanup: false
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: PeYxia+LjPhnnWI3b8CbTQNKlpBCXbz4z8P5giElT3yf+jQ4/OpzwsFk92qmxBts5J279afI98E+z9iU0jfXtk44mLICuL5sM6wuoKp9RLAHIYqZq3CQS4XOC4Rst2+Z7akyGDkV00GhQEUITAuuzOj6We84z1ezHp/6lPFMd4YKEUWh1Z7wVwE2LiTzEEIvGccEed476Z4fKT4dTE9sngM+zWnr5oOcc8113u12jd/h+4dGmofJGB0pFQRPNE//dNYDPTnpohuWLSPcnflc/YZGoyC1dMXycnjKvgJUsaij+b7UvajrZFod5aIlidDMnXwMCvCYfxN7wR/DNqS1L3vIBWoa2PCevJ31VoZ/LJTFpzUneTBitfJSRcKhY7KkOws6BQV20QF1nkXuqe9xdr0hdAas6Yv//kFRBwB0tIO0hHiyntNqWpal3nrrwRMIdGsPDc6H/HwxXHlGLdtgtnq4sn9dprLAo6F6IoBhDgJMgBioRbRGcT3JV2Olzy5C9SSJL9KLINIhsA0p2EcFexchRdhxwSJiISPF0mH7n3LHziEosdpT3GzLaEPu3UYm98UxKGE3EaO3kzs2+a0ahkiqJzQ8EfraW+n99Jv7nB9VsLyfptPmsoD6Vu8eAf4D3ftxKMMt6nID6Bon9tFxdUKydvA248YzwJkmn7JYDKc=
  - secure: n0tBGf/7dpBkaCU0btO2dm3p/fWZ0NRnTlmCkQzaGIUc3Bb0U5WVv1ZrmUburlrr7AtaEVqDIEEo8Lxuo/C1yJjhR8ZaAQ/tvsq92US7c2bqFGrbJxFR7AnKPYXHCa0hQyu8dK0GPRbM52pLk5c4wFtr1J7i+Fo6qelYUFcfJJlILO2t9GVgYKC+ttCHUyp0cWyPm22VRdasCU3QbKwX0iDwMGIgpwLS1gx0G1CC1MBLbc3LlytlFSXhnMRbFFfmQd94XXoPQZUzEKa/IkrzQyrV9aC8DfNBhvS0UWmx7SlfS6tagMj66sSpzuKxOa4j8yNPlD6vHz3DPhvJilMKshKlVVjXUx6XGs3HHiHWzFcC8HyhWYSaHrG9a7sBv5vVD3ss/EPOupuVJN6doHyvzO5eEGSbH9AyGf4YzJhqrfho+AxVIzp6ftRTMvJphiusTC01FH+gFzeJl9g5QF/cz50cu37CwMTJ2J8hfm7t9JJm1B9AkdUHPny2bRRVRp0R4vfVf3sopntL+aojG/dsxLXl/6TZBLgs/7PTxE8wascUlHibGytXGfFcNmsGqRQqPJG1XaQhYtzPmnfPx3mPl/m1Bbq4AVrr4HGWluqcIqAo30ODEzv3PUZhTi/vGW+b6vhkVwqFabKhDlBem7YnbW4OM4xogTrZFPGn9zEMZpQ=
